# Добавление необходимой библиотеки

In [1]:
import numpy as np

# Создание матриц для игры

Условие задачи "Семейный спор"

In [2]:
table = np.array([
    [
        [4, 0],
        [0, 1]
    ],
    [
        [1, 0],
        [0, 4]
    ],
])
table

array([[[4, 0],
        [0, 1]],

       [[1, 0],
        [0, 4]]])

Условие задачи "Дилемма заключенного"

In [3]:
table = np.array([
    [
        [-1, -10],
        [0, -8]
    ],
    [
        [-1, 0],
        [-10, -8]
    ],
])
table

array([[[ -1, -10],
        [  0,  -8]],

       [[ -1,   0],
        [-10,  -8]]])

Мое условие

In [4]:
table = np.array([
    [
        [4, 0, 2],
        [7, 2, 4],
        [1, 5, 3]
    ],
    [
        [4, 1, 3],
        [3, 4, 5],
        [2, 6, 4]
    ],
])
table

array([[[4, 0, 2],
        [7, 2, 4],
        [1, 5, 3]],

       [[4, 1, 3],
        [3, 4, 5],
        [2, 6, 4]]])

# Равновесие в доминирующих стратегиях

In [5]:
def find_dominate_line(matrix):  # Функция для нахождения доминирующей строки
    dominated = set()
    been_dominating = set()

    for i in range(len(matrix)):
        for j in range(len(matrix)):
            if i == j:
                continue
            if all(map(lambda x: x[0] < x[1], zip(matrix[i], matrix[j]))):
                dominated.add(j)
                been_dominating.add(i)
    result = list(dominated.difference(been_dominating))
    return None if len(result) == 0 else result[0]

In [6]:
dominants = [find_dominate_line(table[i]) for i in range(len(table))]
print(dominants)

is_equilibrium = len(set(dominants)) == len([i for i in dominants if not i is None])
if is_equilibrium:
    print('Равновесие соблюдено')
else:
    print('Равновесие не соблюдено')

[1, None]
Равновесие не соблюдено


# Равновесие по Нэшу

In [7]:
A = np.argmax(table[0], axis=0)
B = np.argmax(table[1], axis=1)
nesh = []
for i in range(len(A)):
    if A[i] == B[i]:
        nesh.append((A[i], B[i]))

print(f'Точки равновесия по Нэшу: {nesh}')

Точки равновесия по Нэшу: [(2, 2), (1, 1)]


In [8]:
converted_table = [[(None,) for j in range(len(table[0][i]))] for i in range(len(table[0]))]
for i in range(len(converted_table)):
    for j in range(len(converted_table[i])):
        converted_table[i][j] = tuple([table[k][i][j] for k in range(len(table))])
converted_table

[[(4, 4), (0, 1), (2, 3)], [(7, 3), (2, 4), (4, 5)], [(1, 2), (5, 6), (3, 4)]]

# Равновесие по Парето

In [9]:
paretto_points = [i for i in nesh if converted_table[i[1]][i[0]][0] + converted_table[i[1]][i[0]][1] == max([converted_table[j[1]][j[0]][0] + converted_table[j[1]][j[0]][1] for j in nesh])]
print(f'Точки равновесия по Парето: {paretto_points}')

Точки равновесия по Парето: [(2, 2)]


# Равновесие по Штакельбергу
Согласно теореме 8:
__Если игра двух лиц имеет по крайней мере две оптимальные по Парето и одновременно равновесные по Нэшу ситуации с различными векторами выигрышей,
то в игре имеет место борьба за лидерство.__

In [10]:
is_struggle_leadership = len(paretto_points) >= 2 and len(set(nesh)) != 1
if is_struggle_leadership:
    print('Имеет место борьба за лидерство')
else:
    print('Борьбы за лидерство нет')

H = []
for i in range(len(table)):
    leader_index = np.unravel_index(np.argmax(table[i]), table[i].shape)[i]
    sled_index = np.argmax(table[1-i], axis=1-i)[leader_index]
    H.append(tuple(table[i][leader_index][sled_index] for i in range(len(table))))

print(f'Точки равновесия по Штакельбергу: {H}')

Борьбы за лидерство нет
Точки равновесия по Штакельбергу: [(4, 5), (4, 5)]
