# Добавление необходимой библиотеки

In [1]:
import numpy as np
from numpy import linalg as LA

# Создание матриц для игры

Условие задачи "Семейный спор"

In [2]:
table = np.array([
    [
        [4, 0],
        [0, 1]
    ],
    [
        [1, 0],
        [0, 4]
    ],
])
table

array([[[4, 0],
        [0, 1]],

       [[1, 0],
        [0, 4]]])

Условие задачи "Дилемма заключенного"

In [3]:
table = np.array([
    [
        [-1, -10],
        [0, -8]
    ],
    [
        [-1, 0],
        [-10, -8]
    ],
])
table

array([[[ -1, -10],
        [  0,  -8]],

       [[ -1,   0],
        [-10,  -8]]])

Мое условие

In [4]:
table = np.array([
    [
        [4, 0, 2],
        [7, 2, 4],
        [1, 5, 3]
    ],
    [
        [4, 1, 3],
        [3, 4, 5],
        [2, 6, 4]
    ],
])
table

array([[[4, 0, 2],
        [7, 2, 4],
        [1, 5, 3]],

       [[4, 1, 3],
        [3, 4, 5],
        [2, 6, 4]]])

### Нахождение инвертированных таблиц

In [5]:
inv_table = np.array([LA.inv(t) for t in table])
inv_table

array([[[-1.4       ,  1.        , -0.4       ],
        [-1.7       ,  1.        , -0.2       ],
        [ 3.3       , -2.        ,  0.8       ]],

       [[ 0.5       , -0.5       ,  0.25      ],
        [ 0.07142857, -0.35714286,  0.39285714],
        [-0.35714286,  0.78571429, -0.46428571]]])

### Нахождение равновесных векторов выигрыша

In [6]:
v = [1 / ((np.matrix(np.ones(len(t[0]))) *  t * np.matrix(np.ones(len(t))).T).tolist()[0][0]) for t in inv_table]
v

[2.5000000000000018, 3.111111111111113]

### Нахождение значений x, y

In [7]:
x, y = tuple((v[i] * np.matrix(np.ones(len(inv_table[i][0]))) * inv_table[i]).tolist()[0] for i in range(len(v)))
print(x, y)

[0.4999999999999999, 6.661338147750963e-16, 0.5000000000000003] [0.6666666666666667, -0.22222222222222246, 0.555555555555556]


### Принятие решения

In [8]:
if min(x) >= 0 and min(y) >= 0:
    print(f'Найдена ситуация равновесия в смешанных стратегиях с равновесным вектором выигрышей {v}')
else:
    print('Ситуация равновесия в смешанных стратегиях не найдена')

Ситуация равновесия в смешанных стратегиях не найдена
